{
 "title": "Coda: Snarker Performance Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Instance",
    "query": "label_values(node_uname_info{job=~\"$job\",nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "device",
    "label": "NIC",
    "query": "label_values(node_network_info{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
   }
  ]
 },
 "panels": [
  {
   "title": "Allocated Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "BP1-1. Allocated Memory (last 24hr)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
       "legendFormat": "OS Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "OS Used"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "OS Avaliable"
      },
      {
       "expr": "Coda_Runtime_jemalloc_allocated_bytes",
       "legendFormat": "Coda Used"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
       "legendFormat": "Used%"
      }
     ]
    },
    {
     "title": "BP1-2. Allocated Memory (3 hour averages)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[3h])",
       "legendFormat": "OS Total"
      },
      {
       "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[3h]) - avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[3h])",
       "legendFormat": "OS Used"
      },
      {
       "expr": "avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[3h])",
       "legendFormat": "OS Avaliable"
      },
      {
       "expr": "avg_over_time(Coda_Runtime_jemalloc_allocated_bytes[3h])",
       "legendFormat": "Coda Used"
      },
      {
       "expr": "(1 - (avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[3h]) / (avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[3h]))))* 100",
       "legendFormat": "Used%"
      }
     ]
    },
    {
     "title": "BP1-3. Allocated Memory (daily average)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[1d])",
       "legendFormat": "OS Total"
      },
      {
       "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[1d]) - avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[1d])",
       "legendFormat": "OS Used"
      },
      {
       "expr": "avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[1d])",
       "legendFormat": "OS Avaliable"
      },
      {
       "expr": "avg_over_time(Coda_Runtime_jemalloc_allocated_bytes[1d])",
       "legendFormat": "Coda Used"
      },
      {
       "expr": "(1 - (avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[1d]) / (avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[1d]))))* 100",
       "legendFormat": "Used%"
      }
     ]
    }
   ]
  },
  {
   "title": "Allocated Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used% Basic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Allocated CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU (last 24hr)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[5m])) by (instance) *100",
       "legendFormat": "System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[5m])) by (instance) *100",
       "legendFormat": "User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) by (instance) *100",
       "legendFormat": "Iowait"
      },
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) by (instance))*100",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "CPU (3 hour averages)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[3h])) by (instance) *100",
       "legendFormat": "System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[3h])) by (instance) *100",
       "legendFormat": "User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[3h])) by (instance) *100",
       "legendFormat": "Iowait"
      },
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[3h])) by (instance))*100",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "CPU (daily average)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1d])) by (instance) *100",
       "legendFormat": "System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1d])) by (instance) *100",
       "legendFormat": "User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1d])) by (instance) *100",
       "legendFormat": "Iowait"
      },
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[1d])) by (instance))*100",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Current Snark worker fee for a snarker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Snark worker fee for a snarker",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Coda_Scan_state_snark_fees_per_block"
      }
     ]
    }
   ]
  },
  {
   "title": "# of snarks created in last block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true
  },
  {
   "title": "# of snarks added in the last block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true
  },
  {
   "title": "# of snarks accepted in the last block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true
  },
  {
   "title": "Snarker fee in the last block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Snarker fee in the last block",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
     "targets": [
      {
       "aliasBy": "Fee",
       "constant": 6.5,
       "dataPath": "currentSnarkWorker",
       "queryText": "query Coda {\n  currentSnarkWorker {\n    fee\n  }\n}\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Total snarker fee’s collect in the last block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Snarker fee in the last block",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 10 },
     "targets": [
      {
       "constant": 6.5,
       "dataPath": "snarkPool",
       "queryText": "query Coda {\n  snarkPool {\n    Fee:fee\n    WordID:workIds\n  }\n}\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Uptime percentage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime percentage (24hr)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400",
       "legendFormat": "Update Rate(24hr)"
      }
     ]
    },
    {
     "title": "Uptime percentage (24hr)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400"
      }
     ]
    },
    {
     "title": "Uptime percentage (7days)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400"
      }
     ]
    },
    {
     "title": "Uptime percentage (30days)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400"
      }
     ]
    }
   ]
  },
  {
   "title": "# of uptime hours",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "Coda_Runtime_process_uptime_ms_total / 1000 / 60 / 60\n",
       "legendFormat": "Hours"
      },
      {
       "expr": "Coda_Runtime_process_uptime_ms_total / 1000 / 60 / 60 / 24",
       "legendFormat": "Days"
      },
      {
       "expr": "Coda_Runtime_process_uptime_ms_total / 1000 / 60 / 60 / 24 / 7",
       "legendFormat": "Week"
      }
     ]
    }
   ]
  },
  {
   "title": "Number of connected peers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of connected peers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "avg(Coda_Network_peers)", "legendFormat": "Number of connected peers" }
     ]
    },
    {
     "title": "Number of connected peers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "avg(Coda_Network_peers)", "legendFormat": "Number of connected peers" }
     ]
    },
    {
     "title": "Number of connected peers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "avg(Coda_Network_peers)", "legendFormat": "Number of connected peers" }
     ]
    }
   ]
  }
 ]
}