{
 "title": "Coda: Block Producer Performance Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Instance",
    "query": "label_values(node_uname_info{job=~\"$job\",nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "device",
    "label": "NIC",
    "query": "label_values(node_network_info{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
   }
  ]
 },
 "panels": [
  {
   "title": "Allocated Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "BP1-1. Allocated Memory (last 24hr)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
       "legendFormat": "OS Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "OS Used"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "OS Avaliable"
      },
      {
       "expr": "Coda_Runtime_jemalloc_allocated_bytes",
       "legendFormat": "Coda Used"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
       "legendFormat": "Used%"
      }
     ]
    },
    {
     "title": "BP1-2. Allocated Memory (3 hour averages)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[3h])",
       "legendFormat": "OS Total"
      },
      {
       "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[3h]) - avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[3h])",
       "legendFormat": "OS Used"
      },
      {
       "expr": "avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[3h])",
       "legendFormat": "OS Avaliable"
      },
      {
       "expr": "avg_over_time(Coda_Runtime_jemalloc_allocated_bytes[3h])",
       "legendFormat": "Coda Used"
      },
      {
       "expr": "(1 - (avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[3h]) / (avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[3h]))))* 100",
       "legendFormat": "Used%"
      }
     ]
    },
    {
     "title": "BP1-3. Allocated Memory (daily average)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[1d])",
       "legendFormat": "OS Total"
      },
      {
       "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[1d]) - avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[1d])",
       "legendFormat": "OS Used"
      },
      {
       "expr": "avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[1d])",
       "legendFormat": "OS Avaliable"
      },
      {
       "expr": "avg_over_time(Coda_Runtime_jemalloc_allocated_bytes[1d])",
       "legendFormat": "Coda Used"
      },
      {
       "expr": "(1 - (avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[1d]) / (avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[1d]))))* 100",
       "legendFormat": "Used%"
      }
     ]
    }
   ]
  },
  {
   "title": "Allocated Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used% Basic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Allocated CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU (last 24hr)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[5m])) by (instance) *100",
       "legendFormat": "System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[5m])) by (instance) *100",
       "legendFormat": "User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) by (instance) *100",
       "legendFormat": "Iowait"
      },
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) by (instance))*100",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "CPU (3 hour averages)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[3h])) by (instance) *100",
       "legendFormat": "System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[3h])) by (instance) *100",
       "legendFormat": "User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[3h])) by (instance) *100",
       "legendFormat": "Iowait"
      },
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[3h])) by (instance))*100",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "CPU (daily average)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1d])) by (instance) *100",
       "legendFormat": "System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1d])) by (instance) *100",
       "legendFormat": "User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1d])) by (instance) *100",
       "legendFormat": "Iowait"
      },
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[1d])) by (instance))*100",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "% of slots | produce blocks for",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Producer Rate (Last 30days)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "Coda_Block_producer_blocks_produced * 100 / Coda_Block_producer_slots_won"
      }
     ]
    },
    {
     "title": "Block Producer Rate (Last 30days)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "Coda_Block_producer_slots_won", "legendFormat": "Slot" },
      {
       "expr": "Coda_Block_producer_blocks_produced",
       "legendFormat": "Produce"
      },
      {
       "expr": "Coda_Block_producer_slots_won - Coda_Block_producer_blocks_produced",
       "legendFormat": "Gap (slot - produce)"
      }
     ]
    }
   ]
  },
  {
   "title": "Slots won",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slots Won (by 1hour)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "delta(Coda_Block_producer_slots_won[1h])",
       "legendFormat": "Slots won"
      }
     ]
    },
    {
     "title": "Slots Won (by 3 hours)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "delta(Coda_Block_producer_slots_won[3h])",
       "legendFormat": "Slots won"
      }
     ]
    },
    {
     "title": "Slots Won (by 1 day)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "delta(Coda_Block_producer_slots_won[1d])",
       "legendFormat": "Slots won"
      }
     ]
    }
   ]
  },
  {
   "title": "Blocks produced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocks produced (by 1 hour)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "delta(Coda_Block_producer_blocks_produced[1h])",
       "legendFormat": "Slots won"
      }
     ]
    },
    {
     "title": "Blocks Produced (by 3 hours)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "delta(Coda_Block_producer_blocks_produced[3h])",
       "legendFormat": "Slots won"
      }
     ]
    },
    {
     "title": "Block Produced (by 1 day)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "delta(Coda_Block_producer_blocks_produced[1d])",
       "legendFormat": "Slots won"
      }
     ]
    }
   ]
  },
  {
   "title": "Time spent verifying VRFs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time spent verifying VRFs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "delta(Coda_Consensus_vrf_evaluations[1h])",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Blockchain Proving Time (Seconds)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true
  },
  {
   "title": "% of blocks produced potential",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "Uptime percentage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime percentage (24hr)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400",
       "legendFormat": "Update Rate(24hr)"
      }
     ]
    },
    {
     "title": "Uptime percentage (24hr)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400"
      }
     ]
    },
    {
     "title": "Uptime percentage (7days)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400"
      }
     ]
    },
    {
     "title": "Uptime percentage (30days)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400"
      }
     ]
    }
   ]
  },
  {
   "title": "# of uptime hours",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "Coda_Runtime_process_uptime_ms_total / 1000 / 60 / 60\n",
       "legendFormat": "Hours"
      },
      {
       "expr": "Coda_Runtime_process_uptime_ms_total / 1000 / 60 / 60 / 24",
       "legendFormat": "Days"
      },
      {
       "expr": "Coda_Runtime_process_uptime_ms_total / 1000 / 60 / 60 / 24 / 7",
       "legendFormat": "Week"
      }
     ]
    }
   ]
  },
  {
   "title": "Block Gossip Latencies by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true
  },
  {
   "title": "Max Observed Block by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true
  },
  {
   "title": "Latest Block in local chain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true
  },
  {
   "title": "Number of connected peers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of connected peers (by 1 hour)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(Coda_Network_peers[1h])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Number of connected peers (by 3 hours)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(Coda_Network_peers[3h])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Number of connected peers (by 1 day)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(Coda_Network_peers[1d])",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "# of delegators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "# of tokens delegated to you",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  },
  {
   "title": "Pending delegations #",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "-------------------- Block Producer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Producer",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "Coda_Block_producer_slots_won", "legendFormat": "{{hostname}}-slots_won" },
      {
       "expr": "Coda_Block_producer_blocks_produced",
       "legendFormat": "{{hostname}}-blocks-produced"
      }
     ]
    },
    {
     "title": "VRF evaluations performed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "Coda_Consensus_vrf_evaluations", "legendFormat": "{{hostname}}" }
     ]
    },
    {
     "title": "BP8. Coda_Cryptography_blockchain_proving_time_ms",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "Coda_Cryptography_blockchain_proving_time_ms",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "BP12. Block Gossip Latencies by Node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "Coda_Block_latency_gossip_time", "legendFormat": "{{hostname}}" }
     ]
    },
    {
     "title": "BP13. Max Observed Block by Node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 13, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "Coda_Transition_frontier_max_blocklength_observed",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  }
 ]
}