{
 "title": "Coda: Block Producer Performance Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Instance",
    "query": "label_values(node_uname_info{job=~\"$job\",nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "device",
    "label": "NIC",
    "query": "label_values(node_network_info{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "BP1-1. Allocated Memory (last 24hr)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
       "legendFormat": "OS Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "OS Used"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "OS Avaliable"
      },
      {
       "expr": "Coda_Runtime_jemalloc_allocated_bytes",
       "legendFormat": "Coda Used"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
       "legendFormat": "Used%"
      }
     ]
    },
    {
     "title": "BP1-2. Allocated Memory (3 hour averages)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[3h])",
       "legendFormat": "OS Total"
      },
      {
       "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[3h]) - avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[3h])",
       "legendFormat": "OS Used"
      },
      {
       "expr": "avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[3h])",
       "legendFormat": "OS Avaliable"
      },
      {
       "expr": "avg_over_time(Coda_Runtime_jemalloc_allocated_bytes[3h])",
       "legendFormat": "Coda Used"
      },
      {
       "expr": "(1 - (avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[3h]) / (avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[3h]))))* 100",
       "legendFormat": "Used%"
      }
     ]
    },
    {
     "title": "BP1-3. Allocated Memory (daily average)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[1d])",
       "legendFormat": "OS Total"
      },
      {
       "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[1d]) - avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[1d])",
       "legendFormat": "OS Used"
      },
      {
       "expr": "avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[1d])",
       "legendFormat": "OS Avaliable"
      },
      {
       "expr": "avg_over_time(Coda_Runtime_jemalloc_allocated_bytes[1d])",
       "legendFormat": "Coda Used"
      },
      {
       "expr": "(1 - (avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[1d]) / (avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[1d]))))* 100",
       "legendFormat": "Used%"
      }
     ]
    }
   ]
  },
  {
   "title": "Allocated Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used% Basic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Allocated CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU (last 24hr)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[5m])) by (instance) *100",
       "legendFormat": "System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[5m])) by (instance) *100",
       "legendFormat": "User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) by (instance) *100",
       "legendFormat": "Iowait"
      },
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) by (instance))*100",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "CPU (3 hour averages)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[3h])) by (instance) *100",
       "legendFormat": "System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[3h])) by (instance) *100",
       "legendFormat": "User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[3h])) by (instance) *100",
       "legendFormat": "Iowait"
      },
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[3h])) by (instance))*100",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "CPU (daily average)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1d])) by (instance) *100",
       "legendFormat": "System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1d])) by (instance) *100",
       "legendFormat": "User"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1d])) by (instance) *100",
       "legendFormat": "Iowait"
      },
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[1d])) by (instance))*100",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "% of slots | produce blocks for",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Block Producer Rate (Last 30days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Coda_Block_producer_blocks_produced * 100 / Coda_Block_producer_slots_won"
    }
   ]
  },
  {
   "title": "Block Producer Rate (Last 30days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "Coda_Block_producer_slots_won", "legendFormat": "Slot" },
    {
     "expr": "Coda_Block_producer_blocks_produced",
     "legendFormat": "Produce"
    },
    {
     "expr": "Coda_Block_producer_slots_won - Coda_Block_producer_blocks_produced",
     "legendFormat": "Gap (slot - produce)"
    }
   ]
  },
  {
   "title": "Slots won",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true
  },
  {
   "title": "Blocks produced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true
  },
  {
   "title": "Time spent verifying VRFs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true
  },
  {
   "title": "Blockchain Proving Time (Seconds)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true
  },
  {
   "title": "% of blocks produced potential",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true
  },
  {
   "title": "-------------------- Block Producer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "Block Producer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Coda_Block_producer_slots_won", "legendFormat": "{{hostname}}-slots_won" },
    {
     "expr": "Coda_Block_producer_blocks_produced",
     "legendFormat": "{{hostname}}-blocks-produced"
    }
   ]
  },
  {
   "title": "VRF evaluations performed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Coda_Consensus_vrf_evaluations", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "BP8. Coda_Cryptography_blockchain_proving_time_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "Coda_Cryptography_blockchain_proving_time_ms",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "BP12. Block Gossip Latencies by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "Coda_Block_latency_gossip_time", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "BP13. Max Observed Block by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 13, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Coda_Transition_frontier_max_blocklength_observed",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Uptime percentage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Uptime percentage (24hr)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400",
     "legendFormat": "Update Rate(24hr)"
    }
   ]
  },
  {
   "title": "Uptime percentage (24hr)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400"
    }
   ]
  },
  {
   "title": "Uptime percentage (7days)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400"
    }
   ]
  },
  {
   "title": "Uptime percentage (30days)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400"
    }
   ]
  },
  { "title": "# of uptime hours", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "Coda_Runtime_process_uptime_ms_total / 1000 / 60 / 60\n",
     "legendFormat": "Hours"
    },
    {
     "expr": "Coda_Runtime_process_uptime_ms_total / 1000 / 60 / 60 / 24",
     "legendFormat": "Days"
    },
    {
     "expr": "Coda_Runtime_process_uptime_ms_total / 1000 / 60 / 60 / 24 / 7",
     "legendFormat": "Week"
    }
   ]
  },
  {
   "title": "Block Gossip Latencies by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true
  },
  {
   "title": "Max Observed Block by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true
  },
  {
   "title": "Latest Block in local chain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true
  },
  {
   "title": "Machine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory (bytes)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "Coda_Runtime_jemalloc_active_bytes",
       "legendFormat": "{{hostname}}-active"
      },
      {
       "expr": "Coda_Runtime_jemalloc_allocated_bytes",
       "legendFormat": "{{hostname}}-alloc"
      },
      {
       "expr": "Coda_Runtime_jemalloc_mapped_bytes",
       "legendFormat": "{{hostname}}--mapped"
      },
      {
       "expr": "Coda_Runtime_jemalloc_resident_bytes",
       "legendFormat": "{{hostname}}-res"
      }
     ]
    },
    {
     "title": "CPU (seconds)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "Coda_Runtime_process_cpu_seconds_total",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "BP11. # of uptime hours:",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "Coda_Runtime_process_uptime_ms_total",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Up",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "up", "legendFormat": "{{hostname}}" }
     ]
    },
    {
     "title": "# of peers seen through gossip net",
     "type": "graph",
     "gridPos": { "h": 8, "w": 15, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "Coda_Network_peers", "legendFormat": "{{hostname}}" }
     ]
    }
   ]
  }
 ]
}